# Generated by Django 5.0.6 on 2024-06-20 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='core_post',
        ),
    ]
